(() => {
  const boardEl=document.getElementById('board'), moveList=document.getElementById('moveList');
  const glyph={r:'車',n:'馬',b:'相',a:'仕',k:'帥',c:'炮',p:'兵',R:'車',N:'馬',B:'象',A:'士',K:'將',C:'砲',P:'卒'};
  const values={k:10000,r:900,n:430,c:450,b:200,a:200,p:100};
  let board,turn='r',selected=null,legal=[],history=[],moves=[],flipped=false,level='medium',gameMode='ai',thinking=false,gameOver=false,lastMove=null,soundOn=true,toastTimer;
  const copyBoard=b=>b.map(row=>row.map(p=>p?{...p}:null));
  const archiveDBName='chuxiaxiangqi-archive',archiveStore='matches',archiveFallbackKey='chuxiaxiangqi-matches';
  function openArchiveDB(){return new Promise((resolve,reject)=>{if(!window.indexedDB){reject(new Error('IndexedDB unavailable'));return;}const request=window.indexedDB.open(archiveDBName,1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(archiveStore))request.result.createObjectStore(archiveStore,{keyPath:'id'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error('Could not open archive database'));request.onblocked=()=>reject(new Error('Archive database is blocked'));});}
  async function readSavedMatches(){try{const db=await openArchiveDB();return await new Promise((resolve,reject)=>{const tx=db.transaction(archiveStore,'readonly'),request=tx.objectStore(archiveStore).getAll();request.onsuccess=()=>resolve(request.result||[]);request.onerror=()=>reject(request.error);});}catch{try{return JSON.parse(localStorage.getItem(archiveFallbackKey)||'[]');}catch{return[];}}}
  async function storeFinishedMatch(match){try{const db=await openArchiveDB();await new Promise((resolve,reject)=>{const tx=db.transaction(archiveStore,'readwrite');tx.objectStore(archiveStore).put(match);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('Could not save match'));});}catch{const list=await readSavedMatches();const next=[match,...list.filter(item=>item.id!==match.id)].slice(0,200);try{localStorage.setItem(archiveFallbackKey,JSON.stringify(next));}catch{throw new Error('Could not save match in this browser');}}}
  async function refreshArchive(){const saved=(await readSavedMatches()).sort((a,b)=>b.finishedAt-a.finishedAt);const totals=saved.reduce((sum,item)=>{sum.red+=item.result==='r'?3:item.result==='draw'?1:0;sum.black+=item.result==='b'?3:item.result==='draw'?1:0;return sum;},{red:0,black:0});document.getElementById('archiveCount').textContent=String(saved.length);document.getElementById('redPoints').textContent=String(totals.red);document.getElementById('blackPoints').textContent=String(totals.black);const list=document.getElementById('archiveRecords');list.innerHTML='';if(!saved.length){const empty=document.createElement('div');empty.className='archive-empty';empty.textContent='完成一局后，棋谱和结果会保存在这里。';list.appendChild(empty);return;}for(const item of saved.slice(0,12)){const details=document.createElement('details');details.className='archive-entry';const summary=document.createElement('summary'),title=document.createElement('span'),name=document.createElement('strong'),meta=document.createElement('small'),score=document.createElement('b');name.textContent=new Date(item.finishedAt).toLocaleString(undefined,{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});const result=item.result==='r'?'红方胜':item.result==='b'?'黑方胜':'和棋',difficultyNames={easy:'简单',medium:'普通',hard:'困难',superhard:'超难',extreme:'极难'},difficulty=item.mode==='ai'?` · ${difficultyNames[item.difficulty]||'普通'}`:'';meta.textContent=`${item.mode==='local'?'双人对抗':'人机对抗'}${difficulty} · ${result} · ${item.moves.length} 步`;score.className='archive-score';score.textContent=`${item.result==='r'?3:item.result==='draw'?1:0} : ${item.result==='b'?3:item.result==='draw'?1:0}`;title.append(name,meta);summary.append(title,score);details.appendChild(summary);const moveListEl=document.createElement('ol');moveListEl.className='archive-moves';for(let i=0;i<item.moves.length;i++){const li=document.createElement('li');li.textContent=item.moves[i].note;moveListEl.appendChild(li);}details.appendChild(moveListEl);list.appendChild(details);}}
  const inside=(x,y)=>x>=0&&x<9&&y>=0&&y<10;
  function initial(){const b=Array.from({length:10},()=>Array(9).fill(null));const back=['r','n','b','a','k','a','b','n','r'];for(let x=0;x<9;x++){b[0][x]={t:back[x],c:'b'};b[9][x]={t:back[x],c:'r'};}[1,7].forEach(x=>{b[2][x]={t:'c',c:'b'};b[7][x]={t:'c',c:'r'};});for(let x=0;x<9;x+=2){b[3][x]={t:'p',c:'b'};b[6][x]={t:'p',c:'r'};}return b;}
  function palace(x,y,c){return x>=3&&x<=5&&(c==='r'?y>=7&&y<=9:y>=0&&y<=2)}
  function pseudo(b,x,y,attacksOnly=false){const p=b[y][x];if(!p)return[];const out=[], add=(a,d)=>{const X=x+a,Y=y+d;if(inside(X,Y)&&(!b[Y][X]||b[Y][X].c!==p.c))out.push([X,Y]);};
    const clear=(X,Y)=>!b[Y][X];
    switch(p.t){case'r':case'R':for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]])for(let X=x+dx,Y=y+dy;inside(X,Y);X+=dx,Y+=dy){if(!b[Y][X])out.push([X,Y]);else{if(b[Y][X].c!==p.c)out.push([X,Y]);break;}}break;
      case'n':case'N':for(const [dx,dy,lx,ly] of [[1,2,0,1],[-1,2,0,1],[1,-2,0,-1],[-1,-2,0,-1],[2,1,1,0],[2,-1,1,0],[-2,1,-1,0],[-2,-1,-1,0]])if(inside(x+lx,y+ly)&&clear(x+lx,y+ly))add(dx,dy);break;
      case'b':case'B':for(const [dx,dy] of [[2,2],[-2,2],[2,-2],[-2,-2]]){const X=x+dx,Y=y+dy;if(inside(X,Y)&&!b[y+dy/2][x+dx/2]&&(p.c==='r'?Y>=5:Y<=4))add(dx,dy);}break;
      case'a':case'A':for(const [dx,dy] of [[1,1],[-1,1],[1,-1],[-1,-1]])if(palace(x+dx,y+dy,p.c))add(dx,dy);break;
      case'k':case'K':for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]])if(palace(x+dx,y+dy,p.c))add(dx,dy);for(let Y=y+(p.c==='r'?-1:1);inside(x,Y);Y+=(p.c==='r'?-1:1)){if(b[Y][x]){if(b[Y][x].t==='k'&&b[Y][x].c!==p.c)out.push([x,Y]);break;}}break;
      case'c':case'C':for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){let screen=false;for(let X=x+dx,Y=y+dy;inside(X,Y);X+=dx,Y+=dy){if(!screen){if(!b[Y][X])out.push([X,Y]);else screen=true;}else if(b[Y][X]){if(b[Y][X].c!==p.c)out.push([X,Y]);break;}}}break;
      case'p':case'P':{const f=p.c==='r'?-1:1;add(0,f);if((p.c==='r'&&y<=4)||(p.c==='b'&&y>=5)){add(1,0);add(-1,0);}}break;
    }return out;
  }
  function kingPos(b,c){for(let y=0;y<10;y++)for(let x=0;x<9;x++)if(b[y][x]?.t==='k'&&b[y][x].c===c)return[x,y];return null;}
  function attacked(b,x,y,by){for(let j=0;j<10;j++)for(let i=0;i<9;i++)if(b[j][i]?.c===by&&pseudo(b,i,j,true).some(([X,Y])=>X===x&&Y===y))return true;return false;}
  function isSafe(b,c){const k=kingPos(b,c);return !!k&&!attacked(b,k[0],k[1],c==='r'?'b':'r');}
  function legalMoves(b,x,y){const p=b[y][x];if(!p)return[];return pseudo(b,x,y).filter(([X,Y])=>{const q=copyBoard(b);q[Y][X]=q[y][x];q[y][x]=null;return isSafe(q,p.c);});}
  function allMoves(b,c){const out=[];for(let y=0;y<10;y++)for(let x=0;x<9;x++)if(b[y][x]?.c===c)for(const [X,Y] of legalMoves(b,x,y))out.push({x,y,X,Y});return out;}
  function render(){boardEl.innerHTML='';const top=document.createElement('div');top.className='palace top';const bottom=document.createElement('div');bottom.className='palace bottom';const river=document.createElement('div');river.className='river';river.innerHTML='<span>楚　河</span><span>漢　界</span>';boardEl.append(top,bottom,river);
    for(let row=0;row<10;row++)for(let col=0;col<9;col++){const x=flipped?8-col:col,y=flipped?9-row:row,cell=document.createElement('div');cell.className='intersection';cell.style.left=`${col*12.5}%`;cell.style.top=`${row*(100/9)}%`;cell.setAttribute('role','gridcell');cell.setAttribute('aria-label',`${y+1}行${x+1}列${board[y][x]?glyph[board[y][x].c==='r'?board[y][x].t:board[y][x].t.toUpperCase()]:''}`);cell.dataset.x=x;cell.dataset.y=y;
      if(selected?.[0]===x&&selected?.[1]===y)cell.classList.add('selected');if(legal.some(m=>m[0]===x&&m[1]===y))cell.classList.add(board[y][x]?'capture':'legal');if(lastMove&&((lastMove.x===x&&lastMove.y===y)||(lastMove.X===x&&lastMove.Y===y)))cell.classList.add('last');
      const p=board[y][x];if(p){const piece=document.createElement('div');piece.className=`piece ${p.c==='r'?'red':'black'}${selected?.[0]===x&&selected?.[1]===y?' selected':''}`;piece.textContent=glyph[p.c==='r'?p.t:p.t.toUpperCase()];cell.appendChild(piece);}cell.addEventListener('click',onCell);boardEl.appendChild(cell);}
  }
  function onCell(e){if(thinking||gameOver||(gameMode==='ai'&&turn!=='r'))return;const cell=e.currentTarget,x=+cell.dataset.x,y=+cell.dataset.y,p=board[y][x];if(selected&&legal.some(m=>m[0]===x&&m[1]===y)){playMove({x:selected[0],y:selected[1],X:x,Y:y},true);return;}if(p?.c===turn){selected=[x,y];legal=legalMoves(board,x,y);render();document.getElementById('statusText').textContent=legal.length?`已选${turn==='r'?'红':'黑'}方棋子 · 点击绿色落点`:'该棋子当前无合法走法';if(!legal.length)toast('这个棋子现在没有合法走法');return;}if(selected){render();toast('请点击棋盘上的绿色落点，棋子只能按象棋规则移动');return;}toast(`请先选择${turn==='r'?'红':'黑'}方棋子`);}
  function notation(m,p,captured){const prefix=p.c==='r'?'红':'黑',piece=glyph[p.c==='r'?p.t:p.t.toUpperCase()],dest=`${String.fromCharCode(Ａ(m.X))}${10-m.Y}`;return `${prefix}${piece} ${dest}${captured?' ×':''}`;}
  function Ａ(x){return 'Ａ'.codePointAt(0)+x;}
  function playMove(m,record=true){const p=board[m.y][m.x],captured=board[m.Y][m.X];history.push({board:copyBoard(board),turn,moves:moves.length,lastMove:lastMove&&{...lastMove}});board[m.Y][m.X]=p;board[m.y][m.x]=null;lastMove={...m};if(record){const note=notation(m,p,captured);moves.push({side:p.c,note});}turn=turn==='r'?'b':'r';selected=null;legal=[];render();updatePanels();if(soundOn)playMoveSound(p.c,gameMode);if(captured?.t==='k'){finish(p.c);return;}if(!allMoves(board,turn).length){finish(p.c);return;}if(turn==='b'&&gameMode==='ai'){thinking=true;updatePanels();setTimeout(()=>{let best;try{best=chooseMove();}catch(error){console.error('电脑走棋失败',error);best=allMoves(board,'b')[0]||null;}thinking=false;if(best)playMove(best,true);else finish('r');},120);}}
  function updatePanels(){document.getElementById('moveCount').textContent=`${Math.ceil(moves.length/2)} 回合`;document.getElementById('undoMove').disabled=history.length<(gameMode==='ai'?2:1)||thinking;document.getElementById('copyRecord').disabled=!moves.length;document.getElementById('statusText').textContent=thinking?'小弈思考中…':`${turn==='r'?'红':'黑'}方走棋`;document.getElementById('turnLabel').textContent=thinking?'电脑思考中':`${turn==='r'?'红':'黑'}方走棋中`;document.querySelector('.turn-indicator').classList.toggle('black-turn',turn==='b');
    if(!moves.length){moveList.innerHTML='<div class="empty-record"><span class="empty-icon">♜</span><strong>棋局尚未开始</strong><small>点击棋子，选择一个交点落子</small></div>';return;}moveList.innerHTML='';for(let i=0;i<moves.length;i+=2){const row=document.createElement('div');row.className='move-row';row.innerHTML=`<span class="n">${String(Math.floor(i/2)+1).padStart(2,'0')}</span><span class="move-red">${moves[i]?.note||'—'}</span><span class="move-black">${moves[i+1]?.note||'…'}</span>`;moveList.appendChild(row);}moveList.scrollTop=moveList.scrollHeight;}
  function evaluate(b){let score=0;for(let y=0;y<10;y++)for(let x=0;x<9;x++){const p=b[y][x];if(!p)continue;let v=values[p.t]||0;if(p.t==='p')v+=(p.c==='r'?6-y:y-3)*8;if(p.t==='n'||p.t==='c')v+=5-(Math.abs(4-x)+Math.abs(4.5-y))*2;score+=p.c==='b'?v:-v;}return score;}
  function movePriority(b,m){const moving=b[m.y][m.x],captured=b[m.Y][m.X];const captureValue=captured?(values[captured.t]||0)*10-(values[moving.t]||0):0;const center=8-(Math.abs(4-m.X)+Math.abs(4.5-m.Y));return captureValue+center;}
  function search(b,depth,alpha,beta,side){if(depth===0)return evaluate(b);let ms=allMoves(b,side);if(!ms.length)return side==='b'?-100000-depth:100000+depth;ms.sort((a,z)=>movePriority(b,z)-movePriority(b,a));const branchLimit=level==='extreme'?12:level==='superhard'?18:Infinity;if(depth>=2&&ms.length>branchLimit)ms=ms.slice(0,branchLimit);if(side==='b'){let best=-Infinity;for(const m of ms){const q=copyBoard(b);q[m.Y][m.X]=q[m.y][m.x];q[m.y][m.x]=null;best=Math.max(best,search(q,depth-1,alpha,beta,'r'));alpha=Math.max(alpha,best);if(beta<=alpha)break;}return best;}let best=Infinity;for(const m of ms){const q=copyBoard(b);q[m.Y][m.X]=q[m.y][m.x];q[m.y][m.x]=null;best=Math.min(best,search(q,depth-1,alpha,beta,'b'));beta=Math.min(beta,best);if(beta<=alpha)break;}return best;}
  function chooseMove(){const ms=allMoves(board,'b');if(!ms.length){finish('r');return null;}const depth={easy:0,medium:1,hard:2,superhard:3,extreme:4}[level]??1;ms.sort((a,z)=>movePriority(board,z)-movePriority(board,a));let best=null,bestScore=-Infinity,alpha=-Infinity;for(const m of ms){const q=copyBoard(board);q[m.Y][m.X]=q[m.y][m.x];q[m.y][m.x]=null;const score=search(q,depth,alpha,Infinity,'r');if(score>bestScore){bestScore=score;best=m;}alpha=Math.max(alpha,bestScore);}return best;}
  function finish(winner){if(gameOver)return;gameOver=true;thinking=false;const redWin=winner==='r';document.getElementById('resultSeal').textContent=redWin?'勝':'和';document.getElementById('resultTitle').textContent=redWin?'恭喜获胜':'本局惜败';document.getElementById('resultMessage').textContent=redWin?'这一局下得漂亮，守住了楚河汉界。':'棋局已分出胜负，再来一局继续挑战。';document.getElementById('modal').classList.add('open');document.getElementById('statusText').textContent=redWin?'红方获胜':'黑方获胜';updatePanels();const match={id:`${Date.now()}-${Math.random().toString(36).slice(2,8)}`,finishedAt:Date.now(),mode:gameMode,difficulty:level,result:winner,moves:moves.map(move=>({side:move.side,note:move.note}))};storeFinishedMatch(match).then(refreshArchive).catch(()=>toast('本局结束，但浏览器未能保存对局记录'));}
  function reset(){board=initial();turn='r';selected=null;legal=[];history=[];moves=[];lastMove=null;gameOver=false;thinking=false;document.getElementById('modal').classList.remove('open');render();updatePanels();}
  function undo(){const count=gameMode==='ai'?2:1;if(thinking||history.length<count)return;let state;for(let i=0;i<count;i++)state=history.pop();board=copyBoard(state.board);turn=state.turn;moves.length=state.moves;lastMove=state.lastMove;gameOver=false;selected=null;legal=[];render();updatePanels();toast(gameMode==='ai'?'已悔去你和电脑的上一步':'已悔去上一步');}
  function toast(s){const el=document.getElementById('toast');el.textContent=s;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2000);}
  function playMoveSound(side,mode){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),now=c.currentTime;const makeTone=(frequency,when,duration,gain,shape)=>{const o=c.createOscillator(),g=c.createGain();o.type=shape;o.frequency.setValueAtTime(frequency,when);g.gain.setValueAtTime(.0001,when);g.gain.exponentialRampToValueAtTime(gain,when+.006);g.gain.exponentialRampToValueAtTime(.0001,when+duration);o.connect(g);g.connect(c.destination);o.start(when);o.stop(when+duration+.01);};if(side==='b'&&mode==='local'){makeTone(330,now,.075,.05,'triangle');makeTone(245,now+.055,.09,.035,'triangle');}else{const base=side==='r'?510:390;makeTone(base,now,.075,.045,'triangle');makeTone(base*1.48,now+.008,.04,.012,'sine');}c.resume?.();setTimeout(()=>c.close().catch(()=>{}),250);}catch{}}
  document.getElementById('newGame').onclick=reset;document.getElementById('playAgain').onclick=reset;document.getElementById('undoMove').onclick=undo;document.getElementById('flipBoard').onclick=e=>{flipped=!flipped;e.currentTarget.setAttribute('aria-pressed',String(flipped));render();};document.getElementById('soundToggle').onclick=e=>{soundOn=!soundOn;e.currentTarget.classList.toggle('off',!soundOn);e.currentTarget.textContent=soundOn?'♫':'♪';toast(soundOn?'音效已开启':'音效已关闭');};
  const themeButton=document.getElementById('themeToggle');let theme='dark';try{theme=localStorage.getItem('chuxiaxiangqi-theme')||'dark';}catch{}document.documentElement.dataset.theme=theme;function updateThemeButton(){const dark=theme==='dark';themeButton.setAttribute('aria-pressed',String(dark));themeButton.setAttribute('aria-label',dark?'切换浅色背景':'切换深色背景');themeButton.title=dark?'切换到浅色背景':'切换到深色背景';themeButton.textContent=dark?'☼':'◐';document.querySelector('meta[name="theme-color"]').content=dark?'#22231f':'#f5f0e7';}updateThemeButton();themeButton.onclick=()=>{theme=theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;try{localStorage.setItem('chuxiaxiangqi-theme',theme);}catch{}updateThemeButton();};
  const stylePicker=document.getElementById('boardStyle');let boardStyle='retro';try{boardStyle=localStorage.getItem('chuxiaxiangqi-board-style')||'retro';}catch{}if(!['classic','retro','dimensional'].includes(boardStyle))boardStyle='retro';stylePicker.value=boardStyle;document.documentElement.dataset.boardStyle=boardStyle;stylePicker.onchange=()=>{boardStyle=stylePicker.value;document.documentElement.dataset.boardStyle=boardStyle;try{localStorage.setItem('chuxiaxiangqi-board-style',boardStyle);}catch{}};
  const difficultyPicker=document.getElementById('difficulty');difficultyPicker.value=level;difficultyPicker.onchange=()=>{level=difficultyPicker.value;toast(`已切换为${difficultyPicker.selectedOptions[0].textContent}难度`);};
  document.getElementById('hintMove').onclick=()=>{if((gameMode==='ai'&&turn!=='r')||thinking||gameOver){toast('当前不能使用提示');return;}const ms=allMoves(board,turn);if(!ms.length)return;let best=ms[0],score=turn==='b'?-Infinity:Infinity;for(const m of ms){const q=copyBoard(board);q[m.Y][m.X]=q[m.y][m.x];q[m.y][m.x]=null;const s=search(q,1,-Infinity,Infinity,turn==='b'?'r':'b');if(turn==='b'?s>score:s<score){score=s;best=m;}}selected=[best.x,best.y];legal=legalMoves(board,best.x,best.y);render();toast(`建议：${notation(best,board[best.y][best.x],board[best.Y][best.X])}`);};
  document.getElementById('gameMode').onchange=e=>{const mode=e.currentTarget.value;if(mode===gameMode)return;if(thinking){e.currentTarget.value=gameMode;toast('电脑思考结束后再切换模式');return;}gameMode=mode;document.querySelector('.difficulty-picker').hidden=gameMode==='local';document.querySelector('.game-options').classList.toggle('local-mode',gameMode==='local');document.getElementById('modeBadgeText').textContent=gameMode==='ai'?'人机对弈':'双人轮流';document.getElementById('opponentAvatar').textContent=gameMode==='ai'?'AI':'双人';document.getElementById('opponentName').textContent=gameMode==='ai'?'棋友 · 小弈':'本地双人对战';document.getElementById('opponentDescription').textContent=gameMode==='ai'?'稳扎稳打的象棋搭档':'红黑双方轮流操作';document.getElementById('redCaption').textContent=gameMode==='ai'?'红方 · 你':'红方 · 玩家一';document.getElementById('blackCaption').textContent=gameMode==='ai'?'黑方 · 电脑':'黑方 · 玩家二';reset();toast(gameMode==='ai'?'已切换为人机对抗':'已切换为双人对抗');};
  document.getElementById('copyRecord').onclick=async()=>{const text=moves.map((m,i)=>i%2===0?`${Math.floor(i/2)+1}. ${m.note}`:`${m.note}\n`).join(' ');try{await navigator.clipboard.writeText(text);toast('棋谱已复制');}catch{toast('当前浏览器不支持复制');}};
  board=initial();render();updatePanels();refreshArchive();
})();
